export enum DiscountType {
	PERCENTAGE = 'PERCENTAGE',
	FLAT = 'FLAT',
	FREE_SHIPPING = 'FREE_SHIPPING',
}

export enum DiscountVoucherType {
	SHIPPING = 'SHIPPING',
	ENTIRE_ORDER = 'ENTIRE_ORDER',
	SPECIFIC_PRODUCT = 'SPECIFIC_PRODUCT',
}
