const exampleTheme = {
	ltr: 'ltr',
	rtl: 'rtl',
	placeholder: 'nima-richtext-placeholder',
	paragraph: 'nima-richtext-paragraph',
	quote: 'nima-richtext-quote',
	heading: {
		h1: 'nima-richtext-heading-h1',
		h2: 'nima-richtext-heading-h2',
		h3: 'nima-richtext-heading-h3',
		h4: 'nima-richtext-heading-h4',
		h5: 'nima-richtext-heading-h5',
	},
	list: {
		nested: {
			listitem: 'nima-richtext-nested-listitem',
		},
		ol: 'nima-richtext-list-ol',
		ul: 'nima-richtext-list-ul list-disc',
		listitem: 'nima-richtext-listitem',
	},
	image: 'nima-richtext-image',
	link: 'nima-richtext-link',
	text: {
		bold: 'nima-richtext-text-bold',
		italic: 'nima-richtext-text-italic',
		overflowed: 'nima-richtext-text-overflowed',
		hashtag: 'nima-richtext-text-hashtag',
		underline: 'nima-richtext-text-underline',
		strikethrough: 'nima-richtext-text-strikethrough',
		underlineStrikethrough: 'nima-richtext-text-underlineStrikethrough',
		code: 'nima-richtext-text-code',
	},
	code: 'nima-richtext-code',
	codeHighlight: {
		atrule: 'nima-richtext-tokenAttr',
		attr: 'nima-richtext-tokenAttr',
		boolean: 'nima-richtext-tokenProperty',
		builtin: 'nima-richtext-tokenSelector',
		cdata: 'nima-richtext-tokenComment',
		char: 'nima-richtext-tokenSelector',
		class: 'nima-richtext-tokenFunction',
		'class-name': 'nima-richtext-tokenFunction',
		comment: 'nima-richtext-tokenComment',
		constant: 'nima-richtext-tokenProperty',
		deleted: 'nima-richtext-tokenProperty',
		doctype: 'nima-richtext-tokenComment',
		entity: 'nima-richtext-tokenOperator',
		function: 'nima-richtext-tokenFunction',
		important: 'nima-richtext-tokenVariable',
		inserted: 'nima-richtext-tokenSelector',
		keyword: 'nima-richtext-tokenAttr',
		namespace: 'nima-richtext-tokenVariable',
		number: 'nima-richtext-tokenProperty',
		operator: 'nima-richtext-tokenOperator',
		prolog: 'nima-richtext-tokenComment',
		property: 'nima-richtext-tokenProperty',
		punctuation: 'nima-richtext-tokenPunctuation',
		regex: 'nima-richtext-tokenVariable',
		selector: 'nima-richtext-tokenSelector',
		string: 'nima-richtext-tokenSelector',
		symbol: 'nima-richtext-tokenProperty',
		tag: 'nima-richtext-tokenProperty',
		url: 'nima-richtext-tokenOperator',
		variable: 'nima-richtext-tokenVariable',
	},
};

export default exampleTheme;
